### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'depth'

### ISSUE THREAD

**Issue by quanqhow** [Huangying-Zhan/DF-VO#23]
After I run this command:
`python run.py -d options/examples/default_configuration.yml`

The results showing below is:
_Save result in result/tmp/0/? [y/n]y
Traceback (most recent call last):
  File "run.py", line 84, in <module>
    vo = DFVO(cfg)
  File "/home/qzhou10/Documents/DF-VO/libs/dfvo.py", line 51, in __init__
    self.setup()
  File "/home/qzhou10/Documents/DF-VO/libs/dfvo.py", line 68, in setup
    self.dataset = Dataset.datasets[self.cfg.dataset](self.cfg)
  File "/home/qzhou10/Documents/DF-VO/libs/datasets/kitti.py", line 68, in __init__
    super(KittiOdom, self).__init__(*args, **kwargs)
  File "/home/qzhou10/Documents/DF-VO/libs/datasets/kitti.py", line 23, in __init__
    super(KITTI, self).__init__(*args, **kwargs)
  File "/home/qzhou10/Documents/DF-VO/libs/datasets/dataset.py", line 31, in __init__
    self.data_dir = self.get_data_dir()
  File "/home/qzhou10/Documents/DF-VO/libs/datasets/kitti.py", line 105, in get_data_dir
    data_dir['depth_src'] = self.cfg.depth.depth_src
AttributeError: 'EasyDict' object has no attribute 'depth'_

Do you know how to solve this problem?
Thanks a lot.

**Comment by Huangying-Zhan** [comment]
HI @quanqhow  could you double check your `default_configuration.yml` and see if `depth` is there.
![image](https://user-images.githubusercontent.com/13748721/115805678-97f31400-a424-11eb-9e18-bf83df487706.png)

**Comment by quanqhow** [comment]
I can confirm that `depth` is there in `default_configuration.yml`.
![image](https://user-images.githubusercontent.com/16968752/115814431-056e5880-a3c3-11eb-85e3-4104a11061ce.png)

**Comment by quanqhow** [comment]
@Huangying-Zhan I found that there's a typo in `depth` part. I have solved this issue, thank you very much.
